/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal_package;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dell
 */
public class Super_Admin2_6 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Super_Admin2_5
     */
    public Super_Admin2_6() {
    initComponents();
    
    // Update table column widths for the 6-column layout
    javax.swing.table.TableColumnModel columnModel = Users.getColumnModel();
    
    // [0] ID
    columnModel.getColumn(0).setPreferredWidth(40);
    columnModel.getColumn(0).setMinWidth(40);
    columnModel.getColumn(0).setMaxWidth(40);
    
    // [1] Name
    columnModel.getColumn(1).setPreferredWidth(150);
    
    // [2] Bus QTY.
    columnModel.getColumn(2).setPreferredWidth(80);
    
    // [3] Time (Now at Index 3)
    columnModel.getColumn(3).setPreferredWidth(180);
    
    // [4] KM (Now at Index 4)
    columnModel.getColumn(4).setPreferredWidth(70);
    
    // [5] Status (Now at Index 5 - No more Index 6!)
    columnModel.getColumn(5).setPreferredWidth(90);
    
    showTableData();
}
    
    public void showTableData() {
    Users.setRowSorter(null);
    try {
        Class.forName("org.sqlite.JDBC");
        Connection con = DriverManager.getConnection("jdbc:sqlite:BBC.db");
        
        String sql = "SELECT * FROM Tbl_destinations"; 
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) Users.getModel();
        model.setRowCount(0);
        
        while(rs.next()) {
            String id = String.valueOf(rs.getInt("De_ID"));
            String name = rs.getString("Name");
            
            String assignBus = rs.getString("assign_bus");
            if (assignBus == null || assignBus.trim().isEmpty()) {
                assignBus = "0";
            }
            
            // Assume 'Schedule' is a column or just use a placeholder for now
            String schedule = "Daily"; // Or rs.getString("Schedule") if you add it to DB
            
            String time = rs.getString("time");
            String km = rs.getString("KM");
            String status = rs.getString("status");

            // Now we have 7 items to match the 7 columns
            Object[] tbData = {id, name, assignBus, time, km, status};
            model.addRow(tbData);
        }
        
        rs.close();
        pst.close();
        con.close();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Users = new javax.swing.JTable();

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");

        jToggleButton1.setText("Add Destination");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Update Destination");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap())
        );

        Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Bus QTY.", "Time", "KM", "Status"
            }
        ));
        jScrollPane1.setViewportView(Users);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 310, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 44, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setBounds(0, 0, 601, 379);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String searchString = jTextField1.getText();

        DefaultTableModel model = (DefaultTableModel) Users.getModel();

        // 2. Create the sorter
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        Users.setRowSorter(trs);

        // 3. Get text from search bar and apply filter
        // "(?i)" makes the search case-insensitive
        String query = jTextField1.getText();
        trs.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Super_Admin2_7 addAdminFrame = new Super_Admin2_7();

        // 2. Find the DesktopPane this frame is currently sitting in
        javax.swing.JDesktopPane desktopPane = getDesktopPane();

        if (desktopPane != null) {
            // 3. Add the new frame to the desktop
            desktopPane.add(addAdminFrame);
            addAdminFrame.setVisible(true);

            // 4. Optional: Close the current list frame if you want to switch views
            // this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Could not find Desktop Pane.");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Super_Admin2_8 addAdminFrame = new Super_Admin2_8();

        // 2. Find the DesktopPane this frame is currently sitting in
        javax.swing.JDesktopPane desktopPane = getDesktopPane();

        if (desktopPane != null) {
            // 3. Add the new frame to the desktop
            desktopPane.add(addAdminFrame);
            addAdminFrame.setVisible(true);

            // 4. Optional: Close the current list frame if you want to switch views
            // this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Could not find Desktop Pane.");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
