/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import config.DBC;
/**
 *
 * @author USER15
 */
public class Login extends javax.swing.JFrame {

   
    public static boolean isLogout = false;
    public Login() {
        initComponents();
        
   
   
username.setText("Enter Username...");
username.setForeground(new java.awt.Color(153, 153, 153)); // Gray

username.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (username.getText().equals("Enter Username...")) {
            username.setText("");
            username.setForeground(java.awt.Color.BLACK);
        }
    }

    @Override
    public void focusLost(java.awt.event.FocusEvent evt) {
        if (username.getText().isEmpty()) {
            username.setText("Enter Username...");
            username.setForeground(new java.awt.Color(153, 153, 153));
        }
    }
});

// ==========================================
// 2. SETUP EMAIL FIELD (jTextField2)
// ==========================================
// Make sure this variable name matches your Email text field!
email.setText("Enter Email...");
email.setForeground(new java.awt.Color(153, 153, 153)); // Gray

email.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (email.getText().equals("Enter Email...")) {
            email.setText("");
            email.setForeground(java.awt.Color.BLACK);
        }
    }

    @Override
    public void focusLost(java.awt.event.FocusEvent evt) {
        if (email.getText().isEmpty()) {
            email.setText("Enter Email...");
            email.setForeground(new java.awt.Color(153, 153, 153));
        }
    }
});

// ==========================================
// 3. SETUP PASSWORD FIELD (jPasswordField1)
// ==========================================
password.setEchoChar((char)0); // Start visible (so user can read "Enter Password")
password.setText("Enter Password");
password.setForeground(new java.awt.Color(153, 153, 153)); // Gray

password.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(password.getPassword());
        if (pass.equals("Enter Password")) {
            password.setText("");
            password.setForeground(java.awt.Color.BLACK);
            password.setEchoChar('*'); // Hide password with stars
        }
    }

    @Override
    public void focusLost(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(password.getPassword());
        if (pass.length() == 0 || pass.equals("")) {
            password.setText("Enter Password");
            password.setForeground(new java.awt.Color(153, 153, 153));
            password.setEchoChar((char)0); // Make text visible again
        }
    }
});


setSize(750, 500);
setLocationRelativeTo(null); // Center screen
    }
String status;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER15\\Downloads\\New folder\\GUI\\Logoo.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(70, 120, 200, 130);

        username.setText("jTextField1");
        jDesktopPane1.add(username);
        username.setBounds(390, 100, 250, 30);

        email.setText("jTextField2");
        jDesktopPane1.add(email);
        email.setBounds(390, 130, 250, 30);

        password.setText("jPasswordField1");
        jDesktopPane1.add(password);
        password.setBounds(390, 160, 250, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("register");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(390, 190, 90, 30);

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 70, 700, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     String qry = "INSERT INTO Tbl_user ( username, email, password ) VALUES ( ?, ?, ?)";
      DBC con = new DBC();  
     con.addRecord (qry, username.getText(), email.getText(), password.getText() );
     username.setText("");
     email.setText("");
     password.setText("");
     javax.swing.JOptionPane.showMessageDialog(this, "Account Successfully Registered!");
    
           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
