/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Display;

import Main.User;
import Session.Session_Class;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */

public class User1_2 extends javax.swing.JFrame {
    private int loggedInUserId;
    /**
     * 
     * Creates new form User1_2
     */
    public User1_2(int currentUserId) {
        
        this.loggedInUserId = currentUserId;
        initComponents();
        
        // --- NEW DATE INFO ADDITION ---
        // Prevent the user from selecting a past date for booking
        jDateChooser1.setMinSelectableDate(new Date()); 
        
        loadData();
    }
        

    public User1_2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void loadData() {
        String url = "jdbc:sqlite:BBC.db"; // UPDATE THIS TO YOUR ABSOLUTE PATH IF NEEDED
        
        // STRICT SQL: Ensures the bus has a valid Driver ID and Destination ID (> 0)
        String sql = "SELECT d.Name, d.time, d.KM, b.Plate_No " +
                     "FROM tbl_bus b " +
                     "INNER JOIN tbl_destinations d ON b.De_ID = d.De_ID " +
                     "WHERE b.dr_ID > 0 AND b.De_ID > 0";

        try (Connection conn = DriverManager.getConnection(url);
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); 

            while (rs.next()) {
                String destination = rs.getString("Name");
           
                String time = rs.getString("time");
                String kmStr = rs.getString("KM");
                String plateNo = rs.getString("Plate_No");

                double ticketPrice = 0.0;
                try {
                    String numericKm = kmStr.replaceAll("[^0-9.]", ""); 
                    if (!numericKm.isEmpty()) {
                        double kmValue = Double.parseDouble(numericKm);
                        ticketPrice = kmValue * 15;
                    }
                } catch (NumberFormatException e) {
                    System.out.println("Could not parse KM value: " + kmStr);
                }

                model.addRow(new Object[]{
                    destination, 
                  
                    time, 
                    kmStr, 
                    String.format("₱%.2f", ticketPrice),
                    plateNo
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Destination", "Time", "KM", "Ticket", "Plate No."
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 120, 452, 250);

        jLabel1.setText("Choose a date");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(71, 219, 125, 28);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 250, 72, 23);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(560, 180, 125, 35);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pp.jpg"))); // NOI18N
        jLabel6.setText("jLabel4");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Profile");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo_pp.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" TRAVEL HUB");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(244, 244, 244)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 773, 60);

        jPanel7.setBackground(new java.awt.Color(0, 0, 153));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" @ All Rigths Reserved.");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 440, 774, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 60, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(790, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a destination from the table by clicking on a row!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String targetDestination = jTable1.getValueAt(selectedRow, 0).toString().trim();
        // FIX 1: Array index changed from 5 to 4 to match the 5th column!
        String targetPlate = jTable1.getValueAt(selectedRow, 4).toString().trim(); 
        
        java.util.Date date = jDateChooser1.getDate();
        
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Please select a valid date from the calendar!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MM/dd/yy");
        String selectedDate = sdf.format(date); 

        // CRITICAL: Update this to your absolute path if needed!
        String url = "jdbc:sqlite:BBC.db"; 
            
        int deId = 0, drId = 0, busId = 0, maxSeats = 0;
        String plateNo = "", kmStr = "";
        double price = 0.0;
        boolean destFound = false;

        int currentUserId = Session.Session_Class.loggedUserId;
        if (currentUserId == 0) { currentUserId = 10; }

        try (Connection conn = DriverManager.getConnection(url)) {
            
            // --- STEP 2: READ DESTINATION INFO ---
            String selectSql = "SELECT d.De_ID, d.KM, b.dr_ID, b.Plate_No, b.Bus_ID, b.seats " +
                               "FROM tbl_destinations d " +
                               "INNER JOIN tbl_bus b ON d.De_ID = b.De_ID " +
                               "WHERE d.Name = ? AND b.Plate_No = ? AND b.dr_ID > 0 AND b.De_ID > 0";
                               
            try (PreparedStatement selectStmt = conn.prepareStatement(selectSql)) {
                selectStmt.setString(1, targetDestination);
                selectStmt.setString(2, targetPlate); 
                
                try (ResultSet rs = selectStmt.executeQuery()) {
                    if (rs.next()) {
                        deId = rs.getInt("De_ID");
                        drId = rs.getInt("dr_ID");
                        plateNo = rs.getString("Plate_No");
                        kmStr = rs.getString("KM");
                        busId = rs.getInt("Bus_ID");
                        maxSeats = rs.getInt("seats");
                        destFound = true;
                    }
                } 
            }
            
            if (!destFound) {
                JOptionPane.showMessageDialog(this, "Error: No fully equipped bus found for this destination.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String numericKm = kmStr.replaceAll("[^0-9.]", ""); 
            if (!numericKm.isEmpty()) price = Double.parseDouble(numericKm) * 15;
            
            // --- STEP 3: CHECK CAPACITY ---
            String countSql = "SELECT COUNT(*) AS booked_seats FROM tbl_booking WHERE De_ID = ? AND Date = ? AND Plate = ?";
            int bookedSeats = 0;
            try (PreparedStatement countStmt = conn.prepareStatement(countSql)) {
                countStmt.setInt(1, deId);
                countStmt.setString(2, selectedDate);
                countStmt.setString(3, targetPlate); 
                try (ResultSet countRs = countStmt.executeQuery()) {
                    if (countRs.next()) bookedSeats = countRs.getInt("booked_seats");
                } 
            }
            
            if (bookedSeats >= maxSeats) {
                JOptionPane.showMessageDialog(this, "Sorry, the bus is fully booked!", "Fully Booked", JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            int displaySeatNumber = bookedSeats + 1; 

            // --- STEP 4: INSERT SEAT FIRST (FIX 2) ---
            int generatedSeatId = -1;
            String insertSeatSql = "INSERT INTO tbl_seat (Bus_ID, SeatNo) VALUES (?, ?)";
            
            // We use RETURN_GENERATED_KEYS to instantly grab the S_id SQLite creates
            try (PreparedStatement insertSeatStmt = conn.prepareStatement(insertSeatSql, java.sql.Statement.RETURN_GENERATED_KEYS)) {
                insertSeatStmt.setInt(1, busId);
                insertSeatStmt.setInt(2, displaySeatNumber);
                insertSeatStmt.executeUpdate();
                
                try (ResultSet generatedKeys = insertSeatStmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        generatedSeatId = generatedKeys.getInt(1); // Grab the new S_id
                    }
                }
            }
            
            if (generatedSeatId == -1) {
                JOptionPane.showMessageDialog(this, "Error: Could not generate a seat ID.", "Database Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // --- STEP 5: INSERT BOOKING (Now safely utilizing the generated S_id) ---
            String insertBookingSql = "INSERT INTO tbl_booking (dr_ID, De_ID, S_id, userid, Plate, Price, Date) VALUES (?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement insertBookingStmt = conn.prepareStatement(insertBookingSql)) {
                insertBookingStmt.setInt(1, drId);
                insertBookingStmt.setInt(2, deId);
                insertBookingStmt.setInt(3, generatedSeatId); // <-- The Bridge is formed!
                insertBookingStmt.setInt(4, currentUserId); 
                insertBookingStmt.setString(5, targetPlate); 
                insertBookingStmt.setString(6, String.valueOf(price)); // Stored as TEXT per your schema
                insertBookingStmt.setString(7, selectedDate);
                insertBookingStmt.executeUpdate();
            }

            // --- STEP 6: GET USER NAME ---
            String passengerName = "Unknown Passenger";
            try {
                String userSql = "SELECT f_name, l_name FROM Tbl_user WHERE userid = ?";
                try (PreparedStatement userStmt = conn.prepareStatement(userSql)) {
                    userStmt.setInt(1, currentUserId);
                    try (ResultSet userRs = userStmt.executeQuery()) {
                        if (userRs.next()) passengerName = userRs.getString("f_name") + " " + userRs.getString("l_name");
                    }
                }
            } catch (Exception nameError) {
                System.out.println("CRASH AVOIDED: Tbl_user query failed: " + nameError.getMessage());
            }
            
            // --- STEP 7: OPEN RECEIPT PAGE ---
            String formattedPrice = String.format("₱%.2f", price);
            
            User1_3 receiptPage = new User1_3(passengerName, targetDestination, selectedDate, String.valueOf(displaySeatNumber), formattedPrice);
            receiptPage.setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Session_Class load = new Session_Class();
        load.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        User mainUserScreen = new User(Session.Session_Class.loggedUserId);
        
        // 2. Make the new screen visible
        mainUserScreen.setVisible(true);
        
        // 3. Close the current screen (User1_1) so it doesn't stay open in the background
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User1_2(1).setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
